package org.pwharned.openapi

case class OpenApiConfig(
    version: String,
    title: String,
    description: Option[String] = None,
    servers: List[server] = Nil
)

// a user can override these in their own code
object OpenApiConfig:
  given default: OpenApiConfig =
    OpenApiConfig(
      version = "1.0",
      title = "My API",
      description = Some("autogenerated by Crassus"),
      servers = List(server(""))
    )
