addSbtPlugin("org.scalameta" % "sbt-native-image" % "0.3.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.7.3")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.6")
addSbtPlugin("net.virtual-void" % "sbt-optimizer" % "0.1.2")
//addSbtPlugin("org.pwharned" % "caseclassgenerator" % "0.1.0-SNAPSHOT")
